### ISSUE TITLE
Error: ENOENT upon running yo keystone-react

### ISSUE THREAD

**Issue by LorbusChris** [leo7568/generator-keystone-react#1]
Hey, I'm new to JS and I am encountering the following error each time I run the yo generator:

`<Error: ENOENT, no such file or directory 'C:\Users\Chris\AppData\Roaming\npm
\node_modules\generator-keystone-react\app\templates\lib\modelToJSON.js'>`

Seems like \lib\modelToJSON.js is needed but missing.

**Comment by LorbusChris** [comment]
@JedWatson I got it to work renaming your model-transform's index.js to modelToJSON.js. However, I assume it will be added to the dependency tree at some point?

The second error I encountered when running yo was the missing folder "routes\lib" which has since been fixed by your latest edit. Getting the Hello World message in the browser now :) 

Also I must say how impressed I am by your work, people at Thinkmill! 
Keystone is awesome and making use of React seems like the right way. I'm really looking forward to seeing this up and running with a nice Elemental UI, for the Admin as well as User sites.

I am still only getting to know the entire node.js thingy, but I'll set some time aside to dive into it a bit more. I hope I'll then be able to start to commit some useful contributions here!

Greetings from Aachen, Germany
Chris

**Comment by JedWatson** [comment]
@LorbusChris sorry for the confusion - I shouldn't have published that version without running a complete from-scratch generation first. I've fixed those up in the generator templates and published a new version (including one just now reimplementing `model-transform` correctly) - so you can check that out if you like, but good work getting it work anyway!

And thanks! we really enjoy making our work available to others, especially when it's appreciated :) Good luck with getting into node.js, keep in touch as you do!

Cheers from Sydney, Australia
Jed
